### PR TITLE
Login/Signup Page

### PR DESCRIPTION
**Pull request by OmPanpatil**
I added the login and signup page at the beginning of the website. please check it

### CODE REVIEW

**Comment by TeekshaHarish** [comment]
Please add the screenshots of the changes you have made and describe them.

**Comment by OmPanpatil** [comment]
IMG_20240325_025126
I have submitted a login and signup page as it was mean to be landing page or starting of the website. Where it will require backend where data will be store of the user under privacy act we won't do or share any of their data which will store into the database and thus it will open as soon as the user enter the website into FunFusion.

**Comment by TeekshaHarish** [comment]
I believe that you should also integrate the backend with the login/signup page so that it actually serves its purpose of authentication

**Comment by OmPanpatil** [comment]
Yes sir, I am learning it now. So, I contributed the frontend part with the
help of HTML, CSS and JavaScript. I will try to learn as much as possible
and will complete it soon!

**Comment by TeekshaHarish** [comment]
@OmPanpatil Okay but the login form shouldn't be above the navbar as the navbar is the topmots elemnt of a webiste. Please create a new file for the login form and add your code in that

**Comment by OmPanpatil** [comment]
> @OmPanpatil Okay but the login form shouldn't be above the navbar as the navbar is the topmots elemnt of a webiste. Please create a new file for the login form and add your code in that

Sure!

**Pull request closed without merging**
